name: CI/CD Pipeline

on:
#  push:
#    branches:
#      - master
  release:
    types:
      - created

jobs:
  build-push-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
#          tags: ${{ secrets.DOCKERHUB_USERNAME }}/weatherapp:latest
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/bs-test:${{ github.event.release.tag_name }}
      
      - uses: azure/setup-kubectl@v2.0
      # Set the target AKS cluster. 
      - uses: Azure/aks-set-context@v1
        name: Setting target AKS Cluster
        with:
          creds: '${{ secrets.AZURE_CREDENTIALS }}'
          cluster-name: BS23-AKS-Cluster
          resource-group: BS23-Test-RG
      
      - uses: Azure/k8s-deploy@v4
        name: Updating K8s Clusters....
        with:
          action: deploy
          namespace: "weatherapp-ns"
          manifests: |
            ./k8s/secrets.yaml
            ./k8s/deployment.yaml
            ./k8s/services.yaml
          images: |
            ${{ secrets.DOCKERHUB_USERNAME }}/bs-test:${{ github.event.release.tag_name }}

